from __future__ import annotations

from typing import Protocol

from app.shared.db.models import RefreshToken, User


class IdentityRepositoryPort(Protocol):
    def get_user_by_email(self, email: str) -> User | None: ...
    def get_user_by_id(self, user_id: str) -> User | None: ...
    def create_user(self, email: str, password_hash: str, timezone: str) -> User: ...
    def create_refresh_token(self, user_id: str, token_hash: str, refresh_days: int) -> RefreshToken: ...
    def get_active_refresh_token(self, token_hash: str) -> RefreshToken | None: ...
