from __future__ import annotations

from typing import Protocol

from app.shared.db.models import JournalEntry


class JournalRepositoryPort(Protocol):
    def create(self, row: JournalEntry) -> JournalEntry: ...
    def list(self, user_id: str, search: str | None = None) -> list[JournalEntry]: ...
    def get(self, journal_id: str, user_id: str) -> JournalEntry | None: ...
    def delete(self, row: JournalEntry) -> None: ...
