from __future__ import annotations

from datetime import date
from typing import Protocol

from app.shared.db.models import Task, TaskActivity


class TaskRepositoryPort(Protocol):
    def create_task(self, task: Task) -> Task: ...
    def list_tasks(self, user_id: str) -> list[Task]: ...
    def get_task(self, task_id: str, user_id: str) -> Task | None: ...
    def delete_task(self, task: Task) -> None: ...
    def find_daily_responses(self, user_id: str, task_ids: list[str], target: date) -> list[TaskActivity]: ...
    def get_activities_in_range(self, user_id: str, task_id: str, from_date: date, to_date: date) -> list[TaskActivity]: ...
