from __future__ import annotations

from typing import Protocol

from app.shared.db.models import Quest, QuestActivity


class QuestRepositoryPort(Protocol):
    def create(self, row: Quest) -> Quest: ...
    def list(self, user_id: str) -> list[Quest]: ...
    def get(self, quest_id: str, user_id: str) -> Quest | None: ...
    def delete(self, row: Quest) -> None: ...
    def add_activity(self, row: QuestActivity) -> None: ...
    def list_activity(self, quest_id: str, user_id: str) -> list[QuestActivity]: ...
