from __future__ import annotations

from typing import Protocol

from app.shared.db.models import Quest, QuestActivity, QuestMilestone


class QuestRepositoryPort(Protocol):
    def create(self, row: Quest) -> Quest: ...
    def list(self, user_id: str) -> list[Quest]: ...
    def get(self, quest_id: str, user_id: str) -> Quest | None: ...
    def delete(self, row: Quest) -> None: ...
    def add_activity(self, row: QuestActivity) -> None: ...
    def list_activity(self, quest_id: str, user_id: str) -> list[QuestActivity]: ...
    def add_milestone(self, row: QuestMilestone) -> QuestMilestone: ...
    def get_milestone(self, quest_id: str, milestone_id: str, user_id: str) -> QuestMilestone | None: ...
    def list_milestones(self, quest_id: str, user_id: str) -> list[QuestMilestone]: ...
    def delete_milestone(self, row: QuestMilestone) -> None: ...
    def next_milestone_sort_order(self, quest_id: str, user_id: str) -> int: ...
